### ISSUE TITLE
TriggerHandlers shouldn't implicitily use the trigger context variables. 

### ISSUE THREAD

**Issue by gdoenlen** [trailheadapps/apex-recipes#17] opened 2020-10-15 19:52 UTC
In your trigger handler [examples](https://github.com/trailheadapps/apex-recipes/blob/master/force-app/main/default/classes/Trigger%20Recipes/AccountTriggerHandler.cls#L25) you implicitly use the context variables of `Trigger.new` and `Trigger.old`. These should be passed in via the constructor instead.

This will promote a better recipe to developers since it will encourage them to pass in the data making their classes easier to test and make them usable outside of the trigger context.

**Comment by codefriar** [comment] 2020-10-15 20:22
@gdoenlen 

I see your point. I'm still hesitant to change this, because I believe the best practice is to establish three layers here:

Trigger
TriggerHandler
BusinessLogicClass

Enabling re-use of the triggerHandler outside of a trigger context is dangerous, permissions wise. I'd rather the re-use happen at the businessLogicClass level, rather than the triggerHandler level. Accessing and assigning the Trigger context variables in the constructor of the trigger handler, means the triggerHandler itself, by design, is useless outside of a trigger context.

Thoughts?

**Comment by gdoenlen** [comment] 2020-10-15 21:38
I guess I don't see that structure right away in this code. 

Upon a closer look it looks like your layering is also based on static context and methods, which I also argue should be done away with and an instance of your business logic class should be passed in. Recipes should be teaching developers to avoid things like static context, blocking functions, and tight coupling to support reuse or at the very least to facilitate easier testing.

**Comment by codefriar** [comment] 2020-10-16 23:23
@gdoenlen Making that structure clearer is something I'm struggling with. It's easy to **talk** about, but hard to call out outside of documentation. Do you have ideas on making that stratification clearer?

I know some people are taught not to use static methods, or that they're an anti-pattern. I feel like they're useful for code that's written for teaching. It makes it easy to quickly execute a block of code for illustration purposes.  Are you referring specifically to say, the AccountServiceLayer? If so, I'm happy to entertain PR's about moving that class to strictly instance methods.

**Comment by sirephil** [comment] 2020-10-19 20:04
I guess I should have checked the other existing issues before posting my similar issue.

Regardless, I find it difficult to see the point in a trigger helper/handler that is actually something other than the business logic. This feels like bloat for no really good reason. Yes, I totally agree that business logic does not belong in a trigger (for how else can I test it outside the context of a DML operation?), but to me that logic is what the trigger needs to invoke in a small number of lines (ideally a single line that uses a dependency injection pattern to get the required helper/handler instance and call the entry point with the trigger data).

Given the significant gap in Apex around dependency injection and mocking, personally I see these latter two as a far more valuable thing to provide a recipe for, using the StubProvider and related techniques to allow unit tests to truly be UNIT tests (not "integration tests") with minimal DML and therefore fast execution.

**Comment by codefriar** [comment] 2020-10-19 21:16
@gdoenlen @sirephil 

I think we can all agree that business logic belongs anywhere **but** the trigger itself.
We want Apex Recipes to reflect best-practices, and at the heart of this issue is what those best practices are. 
I recognize the TriggerHandler here can be a controversial choice, and I wanted to take a moment to provide a detailed why I believe this is the best practice.

Many developers, pass their trigger context variables to the trigger handler explicitly. Apex Recipes' trigger handler does not. This is for a couple of reasons: 

First, is a philosophical one: _just what is a trigger handler?_ In the case of Apex Recipes, TriggerHandlers are intended as a _polyfill_. TriggerHandler.cls, and related ObjectTriggerHandler.cls files exist to bolt features onto triggers that Salesforce doesn't provide. Namely, an ability to order the execution of business logic, loop checking, and conditional execution. These are feature _**I want**_ triggers to have. Since Apex doesn't allow us to refine, redefine, or override Trigger(the namespace/class), these features have to be polyfilled in other ways.

However, since these features are a polyfill, it makes sense to keep them tightly coupled to the Trigger context variables. 

Second, Trust is our #1 value. Which means Security, and secure coding is paramount. Given the way Triggers currently work in Apex, the trigger handler used by Apex Recipes is architected to _renders the trigger handler code itself useless outside of a trigger context_

One of the many things we want to promote with this code is code reuse. However, if logic resides in the trigger handler itself, that code may at times be used outside of a trigger context. Because the context (quiddidy) isn't checked in the code(yet), it has the possibility (and probability) of accidentally leaking permissions when used outside of a trigger context. This is something I've witnessed myself in more than one org. Yes, it's true that all code, regardless of it's potential contexts should check and honor FLS/Crud but in practice, I often don't see that.  

As a Security enhancing polyfill, this TriggerHandler's architectural use of Trigger context variables is intentional, and I contend, best practice. I'm taking this to our team, for further discussion.

As for testing, since every trigger requires _some_ coverage, I test these trigger handlers at three levels:

1. Trigger - omnibus execution of trigger logic. Insert account, check that it is mutated as expected
1. TriggerHandler - that the order of logic is maintained. Data is test-injected via @testVisible class variables. Often, I accomplish include the Trigger level #1 above, here.
1. Unit testing the actual business logic methods. This is where I spend the majority of my time.

Future additions to Apex Recipes include things like the Stub api and other DI pattern best practices.

**Comment by sirephil** [comment] 2020-10-20 07:23
@codefriar the naming of the trigger handler gives no clue to any of what you have discussed above, and there's little apexdoc to explain this to the developer either. Reference off to the origin is clearly needed, but when I'm developing code I'm not going to stop and follow a link to go read the details of how to use something elsewhere.

Now that I am somewhat enlightened, I feel that the naming is very poor. It would be better to call this "TriggerHandler" a "TriggerLogicOrchestrator" and to call the "AccountTriggerHelper" the "AccountTriggerLogicOrchestrator". The use of "Handler" and "Helper" is a poor choice, leaving the reader clueless as to the role and responsibility of these classes.

I think that much of what you explained above should be reproduced in the apexdoc, but more than that there needs to be a deep explanation as to your statement "Because the context (quiddidy) isn't checked in the code(yet), it has the possibility (and probability) of accidentally leaking permissions when used outside of a trigger context" - I fail to understand what you are getting at here.

I also fail to see how this helps coordinate sequencing across multiple, disparate triggers against the same object, including but not limited to across package boundaries. And as to "loop checking", this doesn't appear to consider trigger invocation chunking (for bulk operations), doesn't distinguish between trigger invocation phases and doesn't identify looping against specific instances. To me, therefore, this seems like a really blunt instrument and one that I wouldn't use. Take a look at https://salesforce.stackexchange.com/questions/296745/what-is-a-good-pattern-for-recursion-blocking-in-generic-trigger-handlers/296748#296748

BTW, with appropriate structuring of your code you should be able to perform all testing without the use of the (to me) horrid @TestVisible annotation in your production code. Clearly this would be made easier if Apex supported reflection to the level that Java does.

**Comment by sirephil** [comment] 2020-10-20 07:27
BTW, my issue #24 was not a direct repeat of this issue as it touched on other aspects.

**Comment by codefriar** [comment] 2020-10-20 13:51
@sirephil 

You raise a few interesting points, so I wanted to quickly reply and get your feedback.

1. There's a _lot_ of content coming around this, that references the _handler_ naming convention. I understand what you're saying, though, about the name not being spot on. I can also see the flip side, where someone new to the idea of writing triggers with an associated class wouldn't have preconceived notions of what a 'handler' is. I don't know that there's a happy medium here, but I'm happy to entertain suggestions. `logicOrchestrator` seems a mouthful. 
1. You should also know that there are some major refactorings coming to TriggerHandler in the near-ish future. While none of the planned improvements will change the root of this issue **use of trigger context variables inside a handler class** they do address some of your other comments.
1. I whole-heartedly agree that the ApexDoc for `TriggerHandler` and associated classes needs to be updated with this information. Look for a PR later today, maybe tomorrow if things get busy.
1. You asked for clarification on this sentence: 'Because the context (quiddidy) isn't checked in the code(yet), it has the possibility (and probability) of accidentally leaking permissions when used outside of a trigger context' -- This all comes back to the fact that triggers run in System Mode. In System Mode Object permissions, field-level security, sharing rules aren't applied for the current user. (because there's no user context). This leads to a double-edged sword of issues: If you write your trigger handler logic to execute CRUD and FLS Checks, you're effectively wasting CPU Time, as those will always pass in System mode. On the other hand, if you _do not_ check CRUD and FLS, any re-use of the Trigger Handler's class methods are insecure. in 'the wild' as it were, I've seen a number of orgs who reuse trigger handler code, and don't do security checks and it's caused some issues at times. This architecture prevents that. 
1. Ok, so as far as the features in play here: This helps with multiple triggers on the same object, because the _handler_ class is responsible for calling business logic elsewhere. The only thing this pattern / architecture does differently is that it doesn't contain the trigger logic directly in the handler, but suggests you put it in its own business logic class.  Also, Trigger Chunking executes each chunk in a different transaction - the loop count is to ensure each single transaction doesn't recurse.

**Comment by sirephil** [comment] 2020-10-20 14:57
@codefriar, thanks.

1. It may be a mouthful, but it is expressive. Naming is really important for guiding developers. Sure, find a shorter word, but "Handler" is about as good as "Manager", "Helper" or "Utils" in expressing true meaning.
2. -
3. Looking forward to it.
4. Hang on, all Apex works this way! The Apex code must apply security and sharing EXPLICITLY using the provided mechanisms (or not, as required on a case-by-case basis). For example, I'm happy to accept that a trigger runs implicitly without sharing, but as soon as you call out to a class marked as with sharing, sharing kicks back in. Unless I have really misunderstood what I've experienced.
5. I believe your statement about transactional separation to be incorrect; in my experience all static variables persist between chunk invocations, which are all performed within the outer-most transaction. The same applies for trigger re-entrancy due to the use of process builders, invocable methods, flows etc. Since the "trigger handler" holds the static loopCountMap these counts apply as-is from the first time this static is loaded to the end of the transaction that initiated the first trigger processing. Indeed, these counts will apply across multiple DML operations performed at the highest level within a transaction (e.g. if an app was to first update some Accounts in one DML, then, in a second DML do some updates to some Opportunities related to those accounts which causes further DML on the Accounts from within the Opportunities trigger context, the counts apply within each of the triggers in each of these DMLs). If this were not the case then why are there so many cases where we have to carefully engineer "recursion suppression" like in the stack exchange Q&A I previously cited?

**Comment by msrivastav13** [comment] 2020-10-21 16:14
@sirephil on the sharing we mark the class with `inherited sharing` not with sharing. With `inherited sharing` triggers run in system mode and class with `inherited sharing` means it depends on the caller class.

**Comment by sirephil** [comment] 2020-10-21 16:20
@msrivastav13 my point is that if you have a class `with sharing` then sharing is applied, even when called from a trigger. I wasn't talking about inherited sharing... are you saying that the trigger runs as if it were `inherited sharing`, picking up the sharing from the context of the DML operation?

**Comment by msrivastav13** [comment] 2020-10-21 16:41
@sirephil Sorry for not being explicit! What I meant here is that we mark all the Trigger handler classes to **inherited sharing**. This way we ensure trigger runs in **system** mode. All the service layers marked inherited sharing as well so any class invoking it owns.

For DML if the class is marked inherited it won't pick any permissions which are desired behavior.

For the service layer class, we need to do FLS and object checks before DML.

**Comment by sirephil** [comment] 2020-11-05 07:42
Just pointing out that other parts of my [earlier response](https://github.com/trailheadapps/apex-recipes/issues/17#issuecomment-712914105) have not been replied to.

**Closed** 2020-11-13 00:25 UTC
Labels: no-issue-activity
