### ISSUE TITLE
AccountTrigger/AccountTriggerHelper "best practice pattern" seriously flawed

### ISSUE THREAD

**Issue by sirephil** [trailheadapps/apex-recipes#24] opened 2020-10-19 19:47 UTC
**What is missing from the application? Please describe.**

Looking at the two classes mentioned in the title, it is clear to me that this pattern is sub-optimal.

By not passing the required values from the trigger to the helper method (`run` in this case), this requires the helper to directly access the `Trigger.old`/`new` and other values which prevents the testing of the helper's code outside the context of a DML operation. Given that unit tests that do not execute any DML are by far and a way faster and actually more cleanly focused on what is being unit tested, I cannot agree that this is a "best practice pattern".

**Describe the solution you'd like**

The trigger should pass all necessary Trigger values to the helper, such as `Trigger.old`, `Trigger.new` (or the equivalent maps) and perhaps the phase and type of event if the helper needs them. That way the helper simply acts on data it receives, and can be unit tested outside the trigger context, without any DML operations being required.

It should also be possible to mock out the handler's processing in the context of the trigger itself, so as to:

1. Verify that the trigger invokes the handler (not the handler's behaviour) in the correct scenarios during actual DML operations (thereby verifying that the trigger is well written) and
2. Avoid the actual processing from occurring except in a select few, more "integration level" tests that test the helper's real processing in the context of a real DML operation (thereby verifying that the correct processing is performed in a reduced number of scenarios).

We have accomplished the mockability by using a dependency injection pattern around the StubProvider along with some simple, re-usable StubProviders that perform method invocation counting etc. Such a mocking framework really should be included in the Apex Recipes library.

**Comment by codefriar** [comment] 2020-10-20 02:14
Duplicate of #17

**Closed** 2020-10-20 02:14 UTC
